In [7]:
%load_ext autoreload
%autoreload 2
import pandas as pd
from os import listdir
from os.path import isfile, join
import numpy as np

def get_data_b3():
    path = '../raw_data'
    files = [f for f in listdir(path) if isfile(join(path, f))] 
    list_files = []
    for file in range(0, len(files)):
        list_file = pd.read_excel(f'{path}/{files[file]}', parse_dates=['Data'])
        list_files.append(list_file)
    list_all_files = pd.concat(list_files)
    list_files_s = list_all_files.sort_values(by=['Produto', 'Data'])
    df_files = pd.DataFrame(list_files_s)
    return df_files
df_files = get_data_b3()
df_files

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

,Entrada/Saída,Data,Movimentação,Produto,Instituição,Quantidade,Preço unitário,Valor da Operação
63,Credito,2020-04-17,Transferência - Liquidação,ALSO3 - ALIANSCE SONAE SHOPPING CENTERS S.A. ...,CLEAR CORRETORA - GRUPO XP,10,24,240
62,Credito,2020-04-20,Transferência - Liquidação,ALSO3 - ALIANSCE SONAE SHOPPING CENTERS S.A. ...,CLEAR CORRETORA - GRUPO XP,19,24.5,465.5
47,Debito,2020-05-19,Transferência - Liquidação,ALSO3 - ALIANSCE SONAE SHOPPING CENTERS S.A. ...,CLEAR CORRETORA - GRUPO XP,34,20.82,707.88
85,Credito,2020-06-01,Transferência - Liquidação,ALSO3 - ALIANSCE SONAE SHOPPING CENTERS S.A. ...,CLEAR CORRETORA - GRUPO XP,5,50.5,252.5
38,Debito,2020-06-25,Transferência - Liquidação,ALUP11 - ALUPAR INVESTIMENTO S/A ...,CLEAR CORRETORA - GRUPO XP,35,24.45,855.75
...,...,...,...,...,...,...,...,...
109,Credito,2020-10-12,Dividendo,YDUQ3 - YDUQS PARTICIPACOES S.A,CLEAR CORRETORA - GRUPO XP,30,0.51,15.29
38,Credito,2021-07-12,Dividendo,YDUQ3 - YDUQS PARTICIPACOES S.A,CLEAR CORRETORA - GRUPO XP,30,0.47,14.09
16,Debito,2021-09-22,Transferência - Liquidação,YDUQ3 - YDUQS PARTICIPACOES S.A,CLEAR CORRETORA - GRUPO XP,30,23.64,709.2
66,Credito,2020-02-04,Transferência - Liquidação,YDUQ3 - ESTACIO PARTICIPACOES S.A. ...,CLEAR CORRETORA - GRUPO XP,30,23,690
72,Debito,2021-12-04,Transferência - Liquidação,YDUQ3 - YDUQS PARTICIPACOES S.A. ...,CLEAR CORRETORA - GRUPO XP,25,30.19,754.75

In [8]:
def files_featuring_eng():
    df_files = get_data_b3()
    df_files['Data da compra'] = df_files['Data'].where(df_files['Entrada/Saída'] == 'Credito')
    df_files['Data da venda'] = df_files['Data'].where(df_files['Entrada/Saída'] == 'Debito')
    df_files = df_files[['Produto', 'Data da compra', 'Data da venda', 'Quantidade', 'Preço unitário', 'Valor da Operação', 'Movimentação', 'Instituição']]
    df_files['Quantidade'] = df_files['Quantidade'].apply(lambda x: x.replace(',','.'))
    df_files['Quantidade'] = df_files['Quantidade'].astype(float)
    return df_files
df_files = files_featuring_eng()
df_files

,Produto,Data da compra,Data da venda,Quantidade,Preço unitário,Valor da Operação,Movimentação,Instituição
63,ALSO3 - ALIANSCE SONAE SHOPPING CENTERS S.A. ...,2020-04-17,NaT,10.0,24,240,Transferência - Liquidação,CLEAR CORRETORA - GRUPO XP
62,ALSO3 - ALIANSCE SONAE SHOPPING CENTERS S.A. ...,2020-04-20,NaT,19.0,24.5,465.5,Transferência - Liquidação,CLEAR CORRETORA - GRUPO XP
47,ALSO3 - ALIANSCE SONAE SHOPPING CENTERS S.A. ...,NaT,2020-05-19,34.0,20.82,707.88,Transferência - Liquidação,CLEAR CORRETORA - GRUPO XP
85,ALSO3 - ALIANSCE SONAE SHOPPING CENTERS S.A. ...,2020-06-01,NaT,5.0,50.5,252.5,Transferência - Liquidação,CLEAR CORRETORA - GRUPO XP
38,ALUP11 - ALUPAR INVESTIMENTO S/A ...,NaT,2020-06-25,35.0,24.45,855.75,Transferência - Liquidação,CLEAR CORRETORA - GRUPO XP
...,...,...,...,...,...,...,...,...
109,YDUQ3 - YDUQS PARTICIPACOES S.A,2020-10-12,NaT,30.0,0.51,15.29,Dividendo,CLEAR CORRETORA - GRUPO XP
38,YDUQ3 - YDUQS PARTICIPACOES S.A,2021-07-12,NaT,30.0,0.47,14.09,Dividendo,CLEAR CORRETORA - GRUPO XP
16,YDUQ3 - YDUQS PARTICIPACOES S.A,NaT,2021-09-22,30.0,23.64,709.2,Transferência - Liquidação,CLEAR CORRETORA - GRUPO XP
66,YDUQ3 - ESTACIO PARTICIPACOES S.A. ...,2020-02-04,NaT,30.0,23,690,Transferência - Liquidação,CLEAR CORRETORA - GRUPO XP
72,YDUQ3 - YDUQS PARTICIPACOES S.A. ...,NaT,2021-12-04,25.0,30.19,754.75,Transferência - Liquidação,CLEAR CORRETORA - GRUPO XP

In [9]:
def variable_income():
    df_stock = df_files[df_files['Movimentação'] == 'Transferência - Liquidação']
    df_stock = df_stock[['Produto', 'Data da compra', 'Data da venda', 'Quantidade', 'Preço unitário', 'Valor da Operação']]
    df_stock = df_stock.sort_values(by=['Produto', 'Data da compra', 'Data da venda']).reset_index()
    df_stock['Produto'] = df_stock['Produto'].apply(lambda x: x.split('-')[0].strip())
    return df_stock
df_stock = variable_income()
df_stock

,index,Produto,Data da compra,Data da venda,Quantidade,Preço unitário,Valor da Operação
0,63,ALSO3,2020-04-17,NaT,10.0,24,240
1,62,ALSO3,2020-04-20,NaT,19.0,24.5,465.5
2,85,ALSO3,2020-06-01,NaT,5.0,50.5,252.5
3,47,ALSO3,NaT,2020-05-19,34.0,20.82,707.88
4,55,ALUP11,2020-11-05,NaT,75.0,21.95,1646.25
...,...,...,...,...,...,...,...
102,54,VVAR3,NaT,2020-05-13,100.0,8.45,845
103,19,YDUQ3,2020-08-31,NaT,25.0,27.85,696.25
104,16,YDUQ3,NaT,2021-09-22,30.0,23.64,709.2
105,66,YDUQ3,2020-02-04,NaT,30.0,23,690
106,72,YDUQ3,NaT,2021-12-04,25.0,30.19,754.75

In [10]:
def variable_income_quantity():
    df_stock_buy = df_stock[df_stock['Data da compra'] > '20000101'].groupby('Produto').agg({'Quantidade':'sum'}).reset_index()
    df_stock_sel = df_stock[df_stock['Data da venda'] > '20000101'].groupby('Produto').agg({'Quantidade':'sum'}).transform(lambda x: x *-1).reset_index()
    quantidades_stock = pd.concat([df_stock_sel, df_stock_buy]).reset_index()
    quantidades_prod_stock = quantidades_stock.groupby(['Produto']).sum().reset_index()
    quantidades_prod_stock = pd.DataFrame(quantidades_prod_stock)
    quantidades_prod_stock = quantidades_prod_stock.drop(columns='index')
    quantidades_prod_stock = quantidades_prod_stock.rename(columns={'Quantidade': 'Saldo de ações'})
    return quantidades_prod_stock
quantidades_prod_stock = variable_income_quantity()
quantidades_prod_stock

   Produto  Saldo de ações
0    ALSO3             0.0
1   ALUP11             0.0
2    AMAR3           100.0
3    AZUL4           100.0
4    B3SA3            19.0
5   BPAC11            51.0
6    BPAN4           360.0
7   BRBI11            22.0
8    BRFS3             0.0
9    BRKM5             0.0
10   BRSR6             0.0
11   CASH3            40.0
12   CIEL3           150.0
13   COCE5            17.0
14   CSNA3             0.0
15   CVCB3             0.0
16   DIRR3            70.0
17   ELET3             0.0
18   ENEV3           -45.0
19   GGPS3           100.0
20   GOAU4            45.0
21   HYPE3             0.0
22   IFCM3            41.0
23   ITSA4          -100.0
24   ITUB4             0.0
25   JPSA3            85.0
26   LAME4            28.0
27   LJQQ3           157.0
28   LVTC3            18.0
29   MGLU3            32.0
30   MOVI3           -27.0
31   MTRE3            80.0
32   NTCO3            50.0
33   OIBR3           976.0
34   PARD3             0.0
35   PCAR3             0.0
36   PETR4            60.0
37   PETZ3            42.0
38   RLOG3           100.0
39   RRRP3            40.0
40  SAPR11           -30.0
41   SBFG3            22.0
42   TRIS3             0.0
43   VALE3            45.0
44  VISC11            27.0
45   VULC3          -161.0
46   VVAR3           -90.0
47   YDUQ3             0.0

In [11]:
def vari_quant_prof_loss():
    df_stock_opB = df_stock[df_stock['Data da compra'] > '20000101'].sort_values(['Produto', 'Data da compra']).reset_index()
    df_stock_opS = df_stock[df_stock['Data da venda'] > '20000101'].sort_values(['Produto', 'Data da venda']).reset_index()
    data_buy = []
    data_sell = []
    for lineB in range(0, len(df_stock_opB)):
        for lineS in range(0, len(df_stock_opS)):
            if df_stock_opS.Produto[lineS] == df_stock_opB.Produto[lineB] and df_stock_opS['Data da venda'][lineS] >= df_stock_opB['Data da compra'][lineB]:
                buy = df_stock_opB['Valor da Operação'][lineB]
                sell = df_stock_opS['Valor da Operação'][lineS]
                prod = df_stock_opB['Produto'][lineB]
                datb = df_stock_opB['Data da compra'][lineB]
                dats = df_stock_opS['Data da venda'][lineS]
                data_buy.append([datb, prod, buy])
                data_sell.append([dats, prod, sell])
            if df_stock_opS.Produto[lineS] == df_stock_opB.Produto[lineB] and df_stock_opS['Data da venda'][lineS] <= df_stock_opB['Data da compra'][lineB]:
                sell2 = df_stock_opS['Valor da Operação'][lineS]
                prod2 = df_stock_opB['Produto'][lineB]
                dats2 = df_stock_opS['Data da venda'][lineS]
                data_sell.append([dats2, prod2, sell2])
    buy_stock = pd.DataFrame(data_buy, columns=['Data da compra', 'Produto', 'Compra'])           
    sell_stock = pd.DataFrame(data_sell, columns=['Data da venda', 'Produto', 'Venda']) 
    sell_stock = sell_stock.drop_duplicates()
    df_stock_buy = buy_stock.groupby('Produto').sum().reset_index()
    sell_stock = sell_stock.drop(columns=['Data da venda'])
    lucpre_stock = pd.concat([sell_stock, df_stock_buy]).reset_index()
    df_stock_opB = df_stock_opB.groupby('Produto').sum().reset_index()
    df_stock_opS = df_stock_opS.groupby('Produto').sum().reset_index()
    calcu = []
    for lineB in range(0, len(df_stock_opB)):
        for lineS in range(0, len(df_stock_opS)):
            if df_stock_opS.Produto[lineS] == df_stock_opB.Produto[lineB]:
                prod = df_stock_opB.Produto[lineB]
                cal = df_stock_opS['Valor da Operação'][lineS]-((df_stock_opB['Valor da Operação'][lineB]/df_stock_opB.Quantidade[lineB])*df_stock_opS.Quantidade[lineS])
                calcu.append([prod, cal])

    calcula = pd.DataFrame(calcu, columns=['Produto', 'Lucro/Prejuízo']) 
    return calcula
calcula = vari_quant_prof_loss()
calcula

KeyError: 'Valor da Operação'

In [12]:
buy_stock

NameError: name 'buy_stock' is not defined

In [6]:
def variable_income_b3():
    stock_i = pd.merge(quantidades_prod_stock, calcula, how='left', on='Produto')
    merge_stock = pd.merge(df_stock, stock_i, how='left', on='Produto')
    merge_stock.drop(columns='index', inplace = True)
    merge_stock = merge_stock.sort_values(['Produto', 'Data da compra', 'Data da venda'])
    merge_stock['Lucro/Prejuizo'] = ''
    merge_stock['Saldo das ações'] = ''
    for line in range(0, len(merge_stock)-1):
        if merge_stock['Produto'].iloc[line] != merge_stock['Produto'].iloc[line+1]:
            merge_stock['Lucro/Prejuizo'].iloc[line] = merge_stock['Lucro/Prejuízo'].iloc[line]
            merge_stock['Saldo das ações'].iloc[line] = merge_stock['Saldo de ações'].iloc[line]
        else:
            merge_stock['Lucro/Prejuizo'].iloc[line] = 'nan'
            merge_stock['Saldo das ações'].iloc[line] = 'nan'
    merge_stock['Lucro/Prejuizo'].iloc[len(merge_stock)-1] = merge_stock['Lucro/Prejuízo'].iloc[len(merge_stock)-1]
    merge_stock['Saldo das ações'].iloc[len(merge_stock)-1] = merge_stock['Saldo de ações'].iloc[len(merge_stock)-1]
    merge_stock.drop(columns=['Saldo de ações', 'Lucro/Prejuízo'], inplace=True)
    spreadsheet_to_stock_income_tax = merge_stock.to_excel('../raw_data/files_to_ti/spreadsheet_stock_income_tax.xlsx', index = False)
    return spreadsheet_to_stock_income_tax
spreadsheet_to_stock_income_tax = variable_income_b3()
spreadsheet_to_stock_income_tax

/home/thamirisbrandao/.pyenv/versions/3.8.12/envs/lewagon/lib/python3.8/site-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)